### ISSUE TITLE
Update to Webpack 3

### ISSUE THREAD

**Issue by lionel-bijaoui** [vue-generators/vue-form-generator#349]
I'm going to do this update on the v3 branch.
This is the first step for this future version.
Then, I'm going to use babel-env and try to optimize the build where possible.

**Comment by icebob** [comment]
Great idea!

**Comment by cristijora** [comment]
Maybe as a side note here. We could use https://dependabot.com/
to keep dependencies up to date. It creates PRs with dependency updates and since we have CI with lots of test this would keep the dependencies up to date.

**Comment by lionel-bijaoui** [comment]
@cristijora Isn't it a bit dangerous? Our test must be rock solid if we use that solution

**Comment by cristijora** [comment]
Well unless there are no major upgrades like webpack then I don't see any big issues with that.
It usually provides links to changelogs and if possible compatibility notes.
![image](https://user-images.githubusercontent.com/15955045/32895245-0fd6d976-cae8-11e7-8b6a-415960c6cf46.png)

Since in a npm package like this most of the dependencies are dev-dependencies, the tests are most likely to fail if something goes wrong + the CI would install the new dependencies on these PRs and run the tests against these new deps. Let's see what @icebob thinks here.

**Comment by icebob** [comment]
It would be good. @cristijora Could you configure it for VFG?

**Comment by cristijora** [comment]
@icebob You would have to add the dependabot application to your github account then select the repo. I can do it only for my repos or organizations I am part of but not someone's else repo

**Comment by icebob** [comment]
Thx, in this case, I will add it.

**Comment by lionel-bijaoui** [comment]
I have a working `dev` config ! I need to update some other things and check if everything really work as intended.
Then I will look into the `build` config...

**Comment by lionel-bijaoui** [comment]
@icebob I'm also going to implement [Prettier ](https://github.com/prettier/prettier) into the mix. It is a fantastic tool that will make beautification the same for everyone

**Comment by icebob** [comment]
Great!
