### ISSUE TITLE
Validator.string submit post even if min value is not met

### ISSUE THREAD

**Issue by hogenf** [vue-generators/vue-form-generator#367]
Validator.string dont validate as expected when submit post even if min value is not met.

Exampel:
https://github.com/vue-generators/vue-form-generator/tree/master/examples/post-form 

Simple fiddle:
https://jsfiddle.net/hogen/c3s05r4q/

**Comment by zoul0813** [comment]
In your fiddle, you wrapped VFG in a `<form>` tag.  This is not valid, as the `<form>` is not being interrupted by anything so VFG does not have a chance to stop it.

You should have an "onSubmit" handler associated with the VFG submit button, per the documentation (https://icebob.gitbooks.io/vueformgenerator/content/fields/submit.html).

Do not put VFG inside a of a `<form>` tag, and instead, perform the form post using javascript only if the VFG form is valid.

**Comment by jkosoy** [comment]
🤔 

This seems less than ideal for noscript / SSR solutions. The form won't have anywhere to submit to. Is there an alternative?

**Comment by zoul0813** [comment]
If the field is required, then it should be flagged as required - this will invalidate the field when it’s empty.

If you’re using the async validators, then you’ll need to handle the form submit manually as VFG does not trap this.

noscript and ssr are outside of the scope of VFG since VFG is a client side JavaScript enabled form generator with validation.
