### ISSUE TITLE
Number fields delete '0' and '-' on debounce

### ISSUE THREAD

**Issue by kretep** [vue-generators/vue-form-generator#425]
* **I'm submitting a ...**
  * [x] bug report

* **What is the current behavior?**
Number fields don't handle '0' and '-' in some cases; they are deleted at debounce. To reproduce:
  * https://jsfiddle.net/0mg1v81e/1978/
  * Make sure a valid number > 0 is in the input box
  * Select all text in the input box
  * Type a 0 or - and wait for debounce
  * On debounce, the input box will be emptied

* **More details and clues**
  * When typing a 0 or - for a second time, the value will stay
  * It only seems to happen when you type the 0 or - when all text is selected and when a number > 0 was previously in the box.
  * In the method [formatNumberToModel](https://github.com/vue-generators/vue-form-generator/blob/master/src/fields/core/fieldInput.vue#L87), the newValue is sometimes a number and sometimes a string; I don't understand why.
  * When replacing the isNumber() check with parseFloat, this solves some of the problems.

* **What is the expected behavior?**
  I expect '0' and '-' not to be deleted when entered in a text field

* **Please tell us about your environment:**
  * Version: 2.2.1
  * Browser: Chrome

**Comment by andrelec1** [comment]
Well i have same issue ....
i try to fixe it but ....

![image](https://user-images.githubusercontent.com/3273204/38314067-bf1f3612-3825-11e8-9b1a-db69de2905c4.png)

**Comment by zoul0813** [comment]
‘0’ is number like, but it’s technically a string.  I don’t agree that ‘0’ should be considered a number.  This seems like an issue with the data model as it is storing the value as a string instead of a number.  The input field should be providing the number and not a string representation of the number.

The negative sign should be treated properly though, and we’ll have to address that.  Perhaps by validating it as true while the field has focus, and false when the field loses focus (which would imply the user only typed - into the field which is invalid)

**Comment by kretep** [comment]
This indeed resolves the issue for the zero, but not for the minus sign.

I kind of like your suggestion of handling the validation differently when the field has the focus.

**Comment by zoul0813** [comment]
Looking into it, it's quite complicated to test if the input field has only a "-" in it or not ... the only way I've managed to get a negative into the field is by racing the "debounce" clock which is set to 1s ... we can probably allow this value to be set manually.

The problem is the `<input type="number" />` does not report the `-` value when asking the input for it's value ... it appears to have no knowledge of it.  We could attach a keypress listener and record the keys but that seems a tad overkill.  If a user is entering a number and hesitates at the beginning (the `-` would be the first value entered) then they can simply re-enter it along with the rest of the value ... if you get `-1` or any other value entered before the debounce timeout ... it accepts the `-` and the value becomes a negative number.

I've just updated the input field to support a `debounceFormatTimeout`, which defaults to 1000ms, and will allow you to alter the debounce timing used for numbers and dates on a per-field basis.  A higher level property that changes the default for all fields might be a good idea later.
