### ISSUE TITLE
Checkbox html value

### ISSUE THREAD

**Issue by mix359** [vue-generators/vue-form-generator#444]
Hi to all,

I'm trying to use the checkbox core component in a standard form that submit to a php script.
I haven't found any problem with all the other components, except for this one, because of the missing of value attribute in the html tag.

I've checked into the component and actually the value is a computed property, and that work if you are using the value inside vuejs, but if you are sending the form, the checkbox is ignored because of the missing value in the html tag.

Could you please add a schema option that permit to set the value html option? Something like inputValue (like the inputName)

Thanks
Cheers Mix

**Comment by mix359** [comment]
Dear @lionel-bijaoui 
I've noticed now that you have closed the issue, but I can't see any new options in the documentation or in the source code.
Does this is issue is resolved?
If not, and it's not a problem adding the inputValue to the schema, I can do it and send a PR.

Thanks
Cheers Mix

**Comment by zoul0813** [comment]
@mix359 I've just tested this, and the checkbox component does send data to the server ... "v-model" binds the "value" and triggers the appropriate events... this is a VueJs functionality.

Here's a Fiddle with it working ... 

https://jsfiddle.net/n3gx170a/

If you submit the form, and check the inspector for network traffic, you'll notice that the browser sends "check: on, hello: world" 

To get this working, all I had to do was add the `inputName` property to the schema for the checkbox.  You'll notice two checkboxes in the form, the first is called "id" and the second is "id2" ... "id2" does not get sent to the server because it does not have an `inputName`

**Comment by mix359** [comment]
@zoul0813 thanks for the reply.

Sorry, I've not reported all the detail of the updated situation.
Initially there was a problem that was preventing the component from sending any data, but was probably already fixed, and is currently working for me, simply updating the vuejs and vue-form-generator version.
Now there's still a small problem: I can't decide which value to send if the checkbox is checked... it's always sending the "on" string (like vue normally does for a boolean value in the model).
What I would like to have is an option that set the value attribute of the tag, that is currently set to "on" from the v-model system, if not specified.

Here's an example of what would be a simple vuejs case, where I've set the value to be send to 1:
https://jsfiddle.net/mix359/9msz86Le 

Thanks
Cheers Mix

**Comment by mix359** [comment]
Awsome, I've really missed that property and that should solve the problem!
Many thanks @zoul0813 ;)

PS: I'm not seeing that property in the documentation on gitbooks, can I suggest to add that with some example of usage?

Thanks again
Cheers Mix
