### ISSUE TITLE
Method for clean form

### ISSUE THREAD

**Issue by DmitrijDev** [vue-generators/vue-form-generator#471]
How about method for clean form? 
Some like this.$ref.someForm.clean()

**Comment by zoul0813** [comment]
What do you define as a “clean” form?

**Comment by zoul0813** [comment]
@DmitrijDev if you want to wipe out the form, you can easily do this by just setting the value of the model passed to VFG to an empty object.  VFG is not capable of understanding what a "clean model" looks like in every possible condition, so that is left to the developer to implement outside of VFG.

VFG is reactive, so if the model being used for the form is set to an empty object, VFG will automatically update the form and use the new (empty) values ... essentially resetting the form.
