### ISSUE TITLE
v3 - optional labels

### ISSUE THREAD

**Issue by gapipro** [vue-generators/vue-form-generator#528]
I have a use-case where labels are part of a field it self and are controlled by field because of design requirements. So I would like to have a way to remove label rendering completely. 

I saw that in new version you are offering usage of label templating with slots. But even if slot is empty you still render `label` tag. So for someone to remove label it has to remove it in schema currently.

I would suggest you make some additional form option or something that would indicate what parts of "general" layout should be rendered. 

Current workaround is to ditch label in schema and introduce some other custom property that would act like one.

**Comment by lionel-bijaoui** [comment]
A simple `display: none` is not enough ?

**Comment by gapipro** [comment]
Well it would hide it, but `label` tag is still rendered with `for` pointing to input. Meaning there would always be multiple labels in for same input. Not optimal really.

**Comment by lionel-bijaoui** [comment]
I'm sorry about that (satisfying everyone is hard).
I will show you something soon, but I need time to prepare the release and everything.

It will allow you to change `form-element` with slot and do anything you want.
It is still very complicated, because you will need many function/props/data for things to work nicely.

In the meantime, you can look at [`form-element`](https://github.com/vue-generators/vue-form-generator/blob/v3/src/formElement.vue#L20-L29). This is where it pass data to the fields and is the most important info.

## A micro doc for minimal `form-element`

The minimal props would be `model`, `options`, `field` and `eventBus`

You would need [`fieldID`](https://github.com/vue-generators/vue-form-generator/blob/v3/src/formElement.vue#L103-L106) to generate a unique id for the field.

You would need [`fieldType`](https://github.com/vue-generators/vue-form-generator/blob/v3/src/formElement.vue#L108-L110) to select the correct component.

To deal with errors, you would need to listen to [`@errors-updated`](https://github.com/vue-generators/vue-form-generator/blob/v3/src/formElement.vue#L29) to get the error of the field.
[`@field-touched`](https://github.com/vue-generators/vue-form-generator/blob/v3/src/formElement.vue#L28) tell you the the field have been touched (modified)

---
Let me be clear, you will need to redo almost everything in a slot named `element`. But this way you could literally do whatever you want.
This is still considered experimental and not tested.

**Comment by zoul0813** [comment]
Are you just trying to change the label text dynamically? This should be supported by updating the label text in the schema.

**Comment by zoul0813** [comment]
@gapipro if you're building a custom component to display your dynamic labels, then you can introduce any custom properties into the schema that you need to.

VFG does not prevent you from passing extra properties in a schema, and custom components can introduce and use any properties they wish.

Custom component properties should try to follow the VFG standards, reusing existing properties found commonly throughout the core components.  However, you don't need to follow this standard ...

Unfortunately, I don't think that the solution @lionel-bijaoui is proposing is the best route for you, as you'd essentially have to rebuild the core display of VFG by overriding the slot values for what seems to be a fairly simple request (remove the standard label, and display a custom label directly inside of a component).  Instead, just introduce a property that is specific to your custom component, and have your component handle it accordingly.

**Comment by zoul0813** [comment]
think of `label` as a reserved property, that is common and shared across all VFG fields.  You can introduce a new custom property called "labelText" or "customComponentLabel" (where "customComponent" would be the name of your component ... so the field is specific to your component.

I believe v3 is introducing a standard "property bucket" called "attributes" or something similar ... where custom components can place any extra bits, without overriding VFG core fields.

For example ... 

```
{
  "type": "customComponent",
  "model": "model",
  "attributes": {
    "label": "custom label for your component to use"
  }
}
```

You can also change "attributes" to be the name of your custom component, and store any necessary properties your component needs in this object ... keeping your components custom properties scoped to itself, without littering the fields common scope properties.

**Comment by gapipro** [comment]
Yep thats exactly what I have done. Thanks for help.
