### ISSUE TITLE
Cant use data fields with name other than "model" and "schema"

### ISSUE THREAD

**Issue by CheyenneForbes** [vue-generators/vue-form-generator#550]
* **I'm submitting a ...**
  * [x] bug report
  * [ ] feature request
  * [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Adding objects with a name other than "model" and "schema" will cause the form to be blank, for example
`<vue-form-generator :schema="form7Schema" :model="form7Model" :options="formOptions"></vue-form-generator>`
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
https://jsfiddle.net/qs2pby48/

* **What is the expected behavior?**
I should be able to use any name I want
- **What is the motivation / use case for changing the behavior?**
Having multiple forms in a component
* **Please tell us about your environment:**
Seems to be any

**Comment by zoul0813** [comment]
You're Fiddle works fine, if you reference "form7Schema" and "form7Model" every time you reference the model or schema in the Fiddle ... 

Here's an updated copy of your Fiddle, using the latest Vue and VFG ... (the Fiddle you used had an old copy of VFG and Vue - the same changes also work here as well)

https://jsfiddle.net/rjfz0vkm/1/ 

It wasn't VFG that was erroring, it was Vue generating errors and preventing the code from running because sections of the template referenced "model" or "schema" and those Vue properties did not exist (you changed them to form7*).
