### ISSUE TITLE
Pikaday field error 'Converting circular structure to JSON' when the 'pikadayOptions' property is used

### ISSUE THREAD

**Issue by guzun** [vue-generators/vue-form-generator#561]
* **I'm submitting a ...**
  * [-] bug report

- **Do you want to request a _feature_ or report a _bug_?**
Report a bug

* **What is the current behavior?**
Currently when I try to use the Pikaday field and pass the 'pikadayOptions' property, then the form gives me the following error after the date is selected from the date piker calendar:

 TypeError: Converting circular structure to JSON (in Chrome)
and 
TypeError: "cyclic object value" (in Firefox)

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

https://jsfiddle.net/allexg/6hxq2rbo/19/ - check this jsfiddle to see issue

* **What is the expected behavior?**
The expected behavior is to not have the js error.

* **Please tell us about your environment:**
Vue.js v2.5.20
vue-form-generator v2.1.0
pikaday v1.8.0
moment.js v2.20.1

  * Browser: [all | Crome Version 70.0.3538.110 | Firefox 63.0.3 (64-bit)  ]

- **Other information**
Does anyone know how to fix this issue ?

Thank you.

**Comment by zoul0813** [comment]
This appears to be caused by the fieldPikaday component modifying the 'pikadayOptions' object that was passed in ... it calls lodash's `defaults` method and adds a `field` and `onSelect` to it.  The `field` is a reference to `this.$el` which is likely where the circular reference is coming from.

Also - it looks like your sample was a bit off, you had `format` setup in the pikadayOptions as `"D MMM YYYY"` but the date in the model was `"DD, MM YYYY"` (or MM, DD YYYY)

A working version of your example is here: https://jsfiddle.net/4za6tmuv/ - due to the odd date format, I added the `format` and `toString` options to the example so it can parse and update the values properly as well.

You can't `JSON.stringify` the schema because of the circular reference, and attempting to do so causing the component to fail ... 

I'm creating a PR that should resolve this issue, in the mean time ... just don't `JSON.stringify` the schema.

**Comment by guzun** [comment]
Thank you @zoul0813!
Your solution fixed the issue.
