### ISSUE TITLE
when use multiple validations show multiple errors

### ISSUE THREAD

**Issue by LuuisPortugal** [vue-generators/vue-form-generator#563]
Hello, I'm using your component and I realized that when I use multiple validations in the same field it shows several errors on the page, I'll attach photos from the screen for you to understand.

I'm using this scheme:
```
oSchema  : 
{
  groups : 
  [
    {
      legend : 'Teste',
      fields : 
      [
        {
          type          : "cleave",
          label         : "Data de nascimento",
          model         : "date",
          pattern       : /^\d{2}\/\d{2}\/\d{4}?/,
          required      : true,
          validator     : ["required", "regexp", "number"],
          cleaveOptions : 
          {
            date: true,
            datePattern: ['d', 'm', 'Y'],
            delimiter: '/'
          }
        }
      ]
    }
  ]
}
```

however, using this schema, it generates this output:
![image](https://user-images.githubusercontent.com/8116126/50003332-72b78680-ff8a-11e8-863f-505e5e146602.png)

I would like you to look at this problem, or guide me to the correct form, if there is one.

I imagine that it is a for in errors, and that it could be changed to a first so it showed only the first error, and when that error was corrected then it showed the other error, and so on.

in addition, the component is very good, very versatile, it helped me a lot, I will always use it, congratulations.

thank you so much.

**Comment by zoul0813** [comment]
The `required` validator is only needed if you are not validating anything other than a values existence.  All built-in validators will return a "this field is required" message if `schema.required = true`.

Your example is a bit confusing as well, as the value can't validate against the 'regexp' and the 'number' validator since your 'regexp' would not result in a valid number.

All validators that fail are expected to return the failure messages, and display them.  This allows the user to see all of the errors and correct the problem, rather than fixing one problem only to be displayed another error.

I've pushed a PR that removes duplicate messages from the errors array, which should resolve this issue.  Though you will still see multiple errors if more than one error is generated (and they are unique).
