### ISSUE TITLE
Feature request: Make "errors help-block" div always occupy the same amount of space

### ISSUE THREAD

**Issue by izzyreal** [vue-generators/vue-form-generator#578]
Currently validation states dramatically alter the appearance of the form. Components below a select or input will move up and down depending on whether the "errors help-block" div is attached to the DOM or not.

I would like the form to be stable in size. Make the div always occupy the same amount of space, only change its (or its span's) visibility.

**Comment by zoul0813** [comment]
You can adjust the wrapper class in an override css to account for the errors block

This seems to be a specific layout/presentation request for your use case, so I don’t think this modification will make it into the code.

Especially since form elements can have any number of validation errors, depending on how many validators are attached and how many notices the validatora generate (ie; password validators complaining about complexity).

**Comment by izzyreal** [comment]
I'll give that a shot, thanks. I hope I can make it work, because I'm trying to let the form dictate the size of a modal popup window:
![image](https://user-images.githubusercontent.com/3707432/51230134-44e5a900-195f-11e9-83d5-e0583c0fb9cb.png)
