### ISSUE TITLE
move eslint to devDependencies instead of a dependencies

### ISSUE THREAD

**Issue by goatandsheep** [vue-generators/vue-form-generator#595]
**I'm submitting a ...**
  * [x] bug report

**What is the current behavior?**

I am having eslint version issues / conflicts because of other packages that I'm using

**What is the expected behavior?**

eslint is a devDependency

**What is the motivation / use case for changing the behavior?**

I don't want to bundle it in my app and it is creating a dependency issue

**Please tell us about your environment:**

  * Version: 2.3.4
  * Browser: all
  * Language: es6/7

**Other information**

I'm totally open for discussion if you disagree

**Comment by zoul0813** [comment]
Good point... will gladly take a PR for this, I can't think of any reason it needs to be a dependency off hand.

**Comment by zoul0813** [comment]
FYI - Just noticed that ALL of VFG's dependencies are listed as "devDependencies" inside of `package.json`

I don't believe this issue is valid, as eslint should not be bundled into your app if properly setup and compiled.  Be sure to look into whatever bundler your using (webpack, parcel, etc) and be sure to configure your dist dependencies properly.

When adding VFG to your project, all that is obtained from npmjs is the `src` and `dist` folders.

**Comment by goatandsheep** [comment]
my mistake. I'm not sure what I was looking at. Sorry!
