### ISSUE TITLE
How I can create dependent Drop down List form rest api schema

### ISSUE THREAD

**Issue by bhavesh-786** [vue-generators/vue-form-generator#619]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  * [x] bug report
  * [x] feature request
  * [x] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**

* **What is the current behavior?**

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

* **What is the expected behavior?**

- **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  * Version: [2.X.X | 3.0.0-beta.X]
  * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bhavesh-786** [comment]
How I can create dependent Drop down List form rest api schema. I am getting schema from api dynamically but I want to create dependent drop down for country and city but I am not able to pass form api. Can you please revert if it is possible.

Thank You

**Comment by muschottkey** [comment]
@bhavesh-786 Could you provide a detailed description of what you are trying to do, and how far you have made it so far? If possible, provide executable code using https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).

Nobody will be able to help you if they can't understand what you are looking for, and that is why it is a good thing to fill in the rest of this template:

> **Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.
> 
> * **I'm submitting a ...**
>   
>   * [x]  bug report
>   * [x]  feature request
>   * [ ]  support request => Please do not submit support request here, see note at the top of this template.
> 
> * **Do you want to request a _feature_ or report a _bug_?**
> 
> * **What is the current behavior?**
> 
> * **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
>   https://jsfiddle.net/ or similar (you can use this template as a starting point: https://jsfiddle.net/icebob/0mg1v81e/).
> 
> * **What is the expected behavior?**
> 
> * **What is the motivation / use case for changing the behavior?**
> 
> * **Please tell us about your environment:**
>   
>   * Version: [2.X.X | 3.0.0-beta.X]
>   * Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
>   * Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]
> 
> * **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bhavesh-786** [comment]
Yes sure let me create fiddle and I'll send you

**Comment by bhavesh-786** [comment]
Hello Please check below jsfiddle 
https://jsfiddle.net/vrt2xqf5/
In created()  => this.formData it's coming from my php code I have generated dynamically but here sample data I have pasted. Now what I want I can't pass function from my php controller but I want to change when I click on country base on that city should be filter from my database but It's not working.

I user Onchanged and tried to create an custom function also but it's also not works.

Please check and let me know it's possible or not.

Thank You

**Comment by muschottkey** [comment]
Okay, I see. Then this is not a bug but a support request. This project has a requirement that: 

> **Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

**Please mark your issue as a support request, or move it to stackOverflow**.

Over to your question, yes it is possible to have dynamic lists for selects. According to the documentation at https://vue-generators.gitbook.io/vue-generators/fields/core-fields/select,
the `values` attribute can be a `function`. This means that you can have a dynamically generated list of values since the function is evaluated at runtime to produce an array of values.

It is up to you to decide how to generate the list of values. 

Your options are:
- Using **Vuex**:
Have a vuex store that keeps state. You can then fetch data from the state in the `values` function inside the schema. **This is your best option**.
Inside your cities schema you could simply access the values from the store. E.g.

```js
{
        type: "select",
        label: "City",
        model: "city",
        required:true,
        validator:["required"],
        values: () => store.state.countryCities,
        styleClasses:'col-xs-6'
},
```
and in your country schema you would trigger an action that fetches the cities and populates the store state with the result. E.g.

```js
{
        type: "select",
        label: "Country",
        model: "country",
        required:true,
        validator:["required"],
        values: ['United Kingdom','Romania','Germany'],
        styleClasses:'col-xs-6',
        onChanged: (model, newVal) => store.dispatch('fetchCitiesForCountry', newVal),
 }
```
This assumes that `store` instance is global, but if it is not, you can simply `import/require` it into the file that has the schema.

- `Using` local state:
   -  See https://codepen.io/muschottkey/pen/vqryXz
   -  add an entry for `countryCities` inside the model which will get passed around. `vfg` passes the model data around, meaning that you would be able to access it inside the schema context for the field.
 
  - Create a function e.g. `fetchCitiesForCountry` in your methods that accepts a country and calls an api or whatever to get a list of cities. Your methods would look like:

```js
methods: {
    fetchCitiesForCountry(country) {
        // call an api or access a global variable, or whatever source is getting you data
        // assume doSomethingPromise returns a promise like you'd have with xhr requests
        doSomethingPromise().then((cities) => {
            this.model.countryCities = cities;
       })
    }
}
```

   - Add an `onChanged` function to the country select schema. Follow guide on https://vue-generators.gitbook.io/vue-generators/fields/field_properties . In this function, you emit an event e.g. `this.$emit('fetchCitiesForCountry', payload)`.
Your country schema would look like:
```js
{
        type: "select",
        label: "Country",
        model: "country",
        required:true,
        validator:["required"],
        values:['United Kingdom','Romania','Germany'],
        styleClasses:'col-xs-6',
        onChanged: (model, newVal) => this.$emit('fetchCitiesForCountry', newVal),
 }
```

  - Set up an event listener in `created` hook that listens to the `fetchCitiesForCountry` event. E.g. 
```js
created() {
    this.$on('fetchCitiesForCountry', (country) => this.fetchCitiesForCountry(country));
}
```
Now whenever the country value changes, we emit an event that we listen to in our vue instance and trigger a function that fetches cities and then populates the countryCities. Your city schema would look like:

```js
{
        type: "select",
        label: "City",
        model: "city",
        required:true,
        validator:["required"],
        values: () => this.model.countryCities,
        styleClasses:'col-xs-6'
},
```

**Comment by bhavesh-786** [comment]
@muschottkey : Thank You for your response but this things I am trying to create from my php controller and from there I am not able to add OnChange function into json response.

{
        type: "select",
        label: "Country",
        model: "country",
        required:true,
        validator:["required"],
        values:['United Kingdom','Romania','Germany'],
        styleClasses:'col-xs-6',
        onChanged: (model, newVal) => this.$emit('fetchCitiesForCountry', newVal),
 }

**Comment by muschottkey** [comment]
Then this sounds more like it is related to how to use the php framework than about `vfg`.

I suggest you ask the question in the support forum of the php framework you are using; or stop generating javascript (or atleast the schemas) on the server side so that you can follow the guides provided by this library.

**Comment by bhavesh-786** [comment]
Actually I am try to use vfg for dynamically generate for that's why I am trying to fetch from server side but I am stuck in this dependent select option and I have clicked on support as well.

Thank You

**Comment by bhavesh-786** [comment]
I
