### ISSUE TITLE
Feature request: support for async field.get function

### ISSUE THREAD

**Issue by carrotinside** [vue-generators/vue-form-generator#654]
Hi,

it would be great to have support for "get" function (in schema fields) witch returns "Promise" to be able get values from async api.

Thx

**Comment by zoul0813** [comment]
What would be the use case here?

You can be notified of model changes by listening for model updates event?

**Comment by carrotinside** [comment]
Actually we do it like that:
In component mounted event loads data from async api and then set them to field values prop.
It's works well, but it's difficult to read mainly if there are more such fields.

It will be much simpler if we can feed field values by get function also in async case.

**Comment by zoul0813** [comment]
VFG’s model can be updated outside of VFG... if you’re talking about getting the form values from an async API, you can just set the values on the model directly.

The same is true of the schema object, so if your field schema is retrieved from an API, you can just modify the schema and VFG will automatically update the schema.

Any “get” logic that we would add into VFG, would be so generic that it wouldn’t be worth adding as you’d have to implement everything yourself since we won’t add any API specifics or requirements into the project to allow it to be as flexible as possible.

Closing - will not implement.

**Comment by dflock** [comment]
Probably a good idea to an example of this to the docs, if someone gets the time.

**Comment by zoul0813** [comment]
@dflock There’s no real examples needed? Just use whatever code you use to retrieve your model or schema, and update the components schema/model accordingly?

**Comment by dflock** [comment]
I agree with you - but for some new users, maybe that might not be obvious,
given this ticket?

**Comment by zoul0813** [comment]
Yeah, my concern would be that examples my influence direction, or otherwise imply “The VFG way”, when there is none.

Granted, if someone wants to make examples... I’m all for it :)

**Comment by dflock** [comment]
Yeah, that's a valid point.
